GloboTicket.Client/Controllers/EventCatalogController.cs
using System;
using System.Threading.Tasks;
using GloboTicket.Web.Extensions;
using GloboTicket.Web.Models;
using GloboTicket.Web.Models.Api;
using GloboTicket.Web.Models.View;
using GloboTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace GloboTicket.Web.Controllers
{
    public class EventCatalogController : Controller
    {
        private readonly IEventCatalogService eventCatalogService;
        private readonly IShoppingBasketService shoppingBasketService;
        private readonly Settings settings;

        public EventCatalogController(IEventCatalogService eventCatalogService, IShoppingBasketService shoppingBasketService, Settings settings)
        {
            this.eventCatalogService = eventCatalogService;
            this.shoppingBasketService = shoppingBasketService;
            this.settings = settings;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {
            var currentBasketId = Request.Cookies.GetCurrentBasketId(settings);

            var getBasket = currentBasketId == Guid.Empty ? Task.FromResult<Basket>(null) :
                shoppingBasketService.GetBasket(currentBasketId);

            var getCategories = eventCatalogService.GetCategories();

            var getEvents = categoryId == Guid.Empty ? eventCatalogService.GetAll() :
                eventCatalogService.GetByCategoryId(categoryId);

            await Task.WhenAll(new Task[] { getBasket, getCategories, getEvents });

            var numberOfItems = getBasket.Result?.NumberOfItems ?? 0;

            return View(
                new EventListModel
                {
                    Events = getEvents.Result,
                    Categories = getCategories.Result,
                    NumberOfItems = numberOfItems,
                    SelectedCategory = categoryId
                }
            );
        }

        [HttpPost]
        public IActionResult SelectCategory([FromForm] Guid selectedCategory)
        {
            return RedirectToAction("Index", new { categoryId = selectedCategory });
        }

        public async Task<IActionResult> Detail(Guid eventId)
        {
            var ev = await eventCatalogService.GetEvent(eventId);
            return View(ev);
        }
    }
}

GloboTicket.Client/Controllers/OrderController.cs
using GloboTicket.Web.Models;
using GloboTicket.Web.Models.Api;
using GloboTicket.Web.Models.View;
using GloboTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System;

namespace GloboTicket.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        private readonly Settings settings;

        public OrderController(Settings settings, IOrderService orderService)
        {
            this.settings = settings;
            this.orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            List<Order> orders = await orderService.GetOrdersForUser(settings.UserId);
            var numberOfMessages = (from order in orders
                            where order.Message != null
                            select order).Count();

            bool hasMessages = numberOfMessages > 0;

            var vm = new OrderListViewModel
            {
                HasMessage = hasMessages,
                Orders = orders
            };

            return View(vm);
        }

        public async Task<IActionResult> Detail(Guid orderId)
        {
            var ev = await orderService.GetOrderDetails(orderId);
            return View(ev);
        }

    }
}

GloboTicket.Client/Controllers/ShoppingBasketController.cs
using GloboTicket.Web.Extensions;
using GloboTicket.Web.Models;
using GloboTicket.Web.Models.Api;
using GloboTicket.Web.Models.View;
using GloboTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GloboTicket.Web.Controllers
{
    public class ShoppingBasketController : Controller
    {
        private readonly IShoppingBasketService basketService;
        private readonly IDiscountService discountService;
        private readonly Settings settings;
        private readonly IConfiguration config;

        public ShoppingBasketController(IShoppingBasketService basketService, Settings settings, IDiscountService discountService, IConfiguration configuration)
        {
            this.basketService = basketService;
            this.settings = settings;
            this.discountService = discountService;
            config = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var basketViewModel = await CreateBasketViewModel();

            return View(basketViewModel);
        }

        private async Task<BasketViewModel> CreateBasketViewModel()
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            Basket basket = await basketService.GetBasket(basketId);

            var basketLines = await basketService.GetLinesForBasket(basketId);

            var lineViewModels = basketLines.Select(bl => new BasketLineViewModel
            {
                LineId = bl.BasketLineId,
                EventId = bl.EventId,
                EventName = bl.Event.Name,
                Date = bl.Event.Date,
                Price = bl.Price,
                Quantity = bl.TicketAmount
            });


            var basketViewModel = new BasketViewModel
            {
                BasketLines = lineViewModels.ToList()
            };

            Coupon coupon = null;

            if (basket.CouponId.HasValue)
                coupon = await discountService.GetCouponById(basket.CouponId.Value);

            if (coupon != null)
            {
                basketViewModel.Code = coupon.Code;
                basketViewModel.Discount = coupon.Amount;
            }

            basketViewModel.ShoppingCartTotal = basketViewModel.BasketLines.Sum(bl => bl.Price * bl.Quantity);

            return basketViewModel;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLine(BasketLineForCreation basketLine)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            var newLine = await basketService.AddToBasket(basketId, basketLine);
            Response.Cookies.Append(settings.BasketIdCookieName, newLine.BasketId.ToString());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateLine(BasketLineForUpdate basketLineUpdate)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            await basketService.UpdateLine(basketId, basketLineUpdate);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveLine(Guid lineId)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            await basketService.RemoveLine(basketId, lineId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            if(config["DefaultUserData:UseDefaultData"] == "True")
            {
                BasketCheckoutViewModel vm = new BasketCheckoutViewModel
                {
                    FirstName = config["DefaultUserData:Data:FirstName"],
                    LastName = config["DefaultUserData:Data:LastName"],
                    Email = config["DefaultUserData:Data:Email"],
                    Address = config["DefaultUserData:Data:Address"],
                    City = config["DefaultUserData:Data:City"],
                    Country = config["DefaultUserData:Data:Country"],
                    ZipCode = config["DefaultUserData:Data:ZipCode"],
                    CardNumber = config["DefaultUserData:Data:CardNumber"],
                    CardName = config["DefaultUserData:Data:CardName"],
                    CardExpiration = config["DefaultUserData:Data:CardExpiration"],
                    CvvCode = config["DefaultUserData:Data:CvvCode"],
                };
                return View(vm);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(BasketCheckoutViewModel basketCheckoutViewModel)
        {
            try
            {
                var basketId = Request.Cookies.GetCurrentBasketId(settings);
                if (ModelState.IsValid)
                {
                    var basketForCheckout = new BasketForCheckout
                    {
                        FirstName = basketCheckoutViewModel.FirstName,
                        LastName = basketCheckoutViewModel.LastName,
                        Email = basketCheckoutViewModel.Email,
                        Address = basketCheckoutViewModel.Address,
                        ZipCode = basketCheckoutViewModel.ZipCode,
                        City = basketCheckoutViewModel.City,
                        Country = basketCheckoutViewModel.Country,
                        CardNumber = basketCheckoutViewModel.CardNumber,
                        CardName = basketCheckoutViewModel.CardName,
                        CardExpiration = basketCheckoutViewModel.CardExpiration,
                        CvvCode = basketCheckoutViewModel.CvvCode,
                        BasketId = basketId,
                        UserId = settings.UserId
                    };

                    await basketService.Checkout(basketCheckoutViewModel.BasketId, basketForCheckout);
                    
                    // clear the basket Id, as it's been removed from the cache on checkout
                    Response.Cookies.Delete(settings.BasketIdCookieName);

                    return RedirectToAction("CheckoutComplete");
                }

                return View(basketCheckoutViewModel);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                return View(basketCheckoutViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApplyDiscountCode(string code)
        {
            var coupon = await discountService.GetCouponByCode(code);

            if (coupon == null || coupon.AlreadyUsed) return RedirectToAction("Index");

            //coupon will be applied to the basket
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            await basketService.ApplyCouponToBasket(basketId, new CouponForUpdate() { CouponId = coupon.CouponId });
            await discountService.UseCoupon(coupon.CouponId);

            return RedirectToAction("Index");

        }

        public IActionResult CheckoutComplete()
        {
            return View();
        }
    }
}

GloboTicket.Client/Views/ShoppingBasket/Checkout.cshtml
@model BasketCheckoutViewModel

<h2 class="text-danger">@ViewBag.ErrorMessage</h2>

<form asp-action="Checkout" method="post" class="form-horizontal" role="form">
    <h4>You're just one step away from placing your order.</h4>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>

        </div>
    </div>

    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Address" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="ZipCode" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="ZipCode" class="form-control" />
            <span asp-validation-for="ZipCode" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="City" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Country" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Country" class="form-control" />
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="CardName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="CardName" class="form-control" />
            <span asp-validation-for="CardName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="CardNumber" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="CardNumber" class="form-control" />
            <span asp-validation-for="CardNumber" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="CardExpiration" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="CardExpiration" class="form-control" />
            <span asp-validation-for="CardExpiration" class="text-danger"></span>
        </div>
    </div>
    
    <div class="form-group">
        <label asp-for="CvvCode" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="CvvCode" class="form-control" />
            <span asp-validation-for="CvvCode" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Place order" />
        </div>
    </div>

</form>

GloboTicket.Client/Views/ShoppingBasket/CheckoutComplete.cshtml
<h2>High Five!</h2>

<h3>Your order is now submitted. Check the <a asp-controller="Order" asp-action="Index">orders page</a> for the status of your ticket order</h3>

GloboTicket.Client/Views/ShoppingBasket/Index.cshtml
@model GloboTicket.Web.Models.View.BasketViewModel

<h2>Your shopping cart</h2>
<h4>Here are the tickets for great events currently in your shopping cart.</h4>

<table class="table">
    <thead>
        <tr class="columnHeader">
            <th>EVENT NAME</th>
            <th>DATE</th>
            <th>PRICE PER TICKET</th>
            <th>QUANTITY</th>
            <th>TOTAL</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.BasketLines)
        {
            <tr>
                <td>@line.EventName</td>
                <td>@line.Date.DateTime.ToShortDateString()</td>
                <td class="bold">$@line.Price</td>
                <td>
                    <form asp-action="UpdateLine">
                        <input type="hidden" name="LineId" value="@line.LineId" />
                        <select name="TicketAmount" class="w-25" asp-for="@line.Quantity">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                        <button type="submit" class="filterButton">Update</button>
                    </form>
                </td>
                <td class="bold">$@(line.Price * line.Quantity) </td>
                <td>
                    <a asp-action="RemoveLine" asp-route-lineId="@line.LineId">
                        <img class="cancelIcon" src="~/img/times.svg" />
                    </a>
                </td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" class="text-right bold big">Discount:</td>
            <td class="text-right bold big">
                @Model.Discount.ToString("c")
            </td>
        </tr>
        <tr>
            <td colspan="4" class="text-right bold big">Total:</td>
            <td class="text-right bold big">
                @((Model.ShoppingCartTotal - Model.Discount).ToString("c"))
            </td>
        </tr>
    </tfoot>
</table>

<div class="row">
    <div class="col-9">
        <h4>Enter your discount code here!</h4>

        <form asp-action="ApplyDiscountCode" method="post" class="form-inline" role="form">

            <label class="sr-only">Code</label>
            <input type="text" class="form-control mb-2 mr-sm-2" name="Code" placeholder="ABC-123">
            <input type="submit" class="filterButton" value="Apply" />

        </form>
    </div>
    <div class="col-3">
        <div class="text-center">
            <a class="btn btn-primary" asp-controller="ShoppingBasket" asp-action="Checkout">Check out now!</a>
        </div>
    </div>

</div>


<div class="mt-2">
    <a asp-controller="EventCatalog" asp-action="Index">
        <img class="backIcon" src="~/img/arrow-down.svg" /> Back to event catalog
    </a>
</div>